[package]
name = "orbsim"
version = "0.1.0"
authors = ["toasthunter"]
description = "A Sun-Earth orbital simulation powered by Piston"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
